version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass#123
      MSSQL_PID: Evaluation
    ports:
      - "5268:1433"