version: '3.4'

services:
  sqlserver: 
    container_name: appdb
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass#123
      MSSQL_PID: Evaluation